### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by itsxrp** [ksauraj/global_index_source#12]
Facing this below issue. Please fix
couldn't fetch token: invalid_grant: maybe token expired? - try refreshing with "rclone config reconnect oned{Sacas}:

**Comment by ksauraj** [comment]
Thanks for informing.

Please update  tool and check if it gets fixed at your end.

```bash
ksau update 
ksau setup
```

You can also join our [telegram channel](https://t.me/ksau_update) for updates about tool.

**Comment by ksauraj** [comment]
Closing this issue as we think we already fixed it. Thanks for informing.
