### ISSUE TITLE
drive.sauraj.cf not working 

### ISSUE THREAD

**Issue by dominator-prime** [ksauraj/global_index_source#15]
Hi
Brother first I want to thank you for KSau uploading support
I'm here just to inform you regarding 
drive.sauraj.cf 
![Screenshot_20240126-165055](https://github.com/ksauraj/global_index_source/assets/18100664/b09a5819-ed6b-48ac-b53d-443fcb268782)
 not working..

Thanks again for helping us
 #developerscommunity

**Comment by ksauraj** [comment]
Hey, thanks for figuring that out. Actually, my domain just expired, and I'm unable to restore it at the moment.

However, all files are still safe as my drive is still there, and it is still hosted on the following domain: `https://my-index-azure.vercel.app/`.

So, you can just replace `drive.sauraj.cf` with `my-index-azure.vercel.app`. I apologize for the inconvenience caused.

So if possible kindly use this alternative for existing urls, and I will soon be changing the domain name in tool.

**Comment by ksauraj** [comment]
@Vikas-V2 just update via `ksau update`  your tool and check if the problem still persist or not.

**Comment by dominator-prime** [comment]
> @Vikas-V2 just update via `ksau update` your tool and check if the problem still persist or not.

thanks for quick response   :)
