### ISSUE TITLE
KSAU Failed to upload file

### ISSUE THREAD

**Issue by itsxrp** [ksauraj/global_index_source#9]
Initializing process, might take up to 10 seconds...
Starting upload...
2023/07/25 08:43:31 Failed to create file system for destination "oned:/XRP/": failed to get root: Get "https://graph.microsoft.com/v1.0/drives/b!R9qYaJBS00Wq1tHwO7Gygz8QcXaSExpMsAE7NdWk7ERfZjfjZ2JwR6-0qKEK0wlI/root": couldn't fetch token: invalid_grant: maybe token expired? - try refreshing with "rclone config reconnect oned{Sacas}:"

**Comment by ksauraj** [comment]
Sorry for the inconvenience caused. Could you please follow the steps below and try uploading something again? Also, remember to report the outcome.
```bash
ksau update
ksau setup
```

**Comment by itsxrp** [comment]
Issue fixed pl.
Thanks alot for that fast response.
